### PR TITLE
Added /heartbeat url endpoint to webhook

### PR DESCRIPTION
**Pull request by thebaron**
Added a /heartbeat endpoint that returns 200 as long as the server is up and working... can be used to ensure server is up for load balancers and/or other HA systems. Probably most useful with mco setups.

### CODE REVIEW

**Comment by rnelson0** [comment]
@thebaron this will need a rebase before we can look at merging.

Are the extra mco params related to the heartbeat endpoint? If not, can you please split up the changes? The endpoint does seem nice to have, though!

**Comment by thebaron** [comment]
Yea, I'll rebase it and also look at the params; it's been a while since I did the PR and I actually forget LOL.

**Comment by rnelson0** [comment]
@thebaron reminder bump

**Comment by thebaron** [comment]
Heya, thanks for the ping, I'll take a look this week and rebase and all that. And pull the extra stuff out.

**Comment by dhollinger** [comment]
@thebaron reminder bump.

**Comment by thebaron** [comment]
Heya, @dhollinger sorry for falling off the face of the Earth. I've rebased the change and removed the mco params .... let's see if this is a bit better.

**Comment by dhollinger** [comment]
@thebaron Can you look into the rubocop rspec failures?

**Comment by thebaron** [comment]
Yea, they look mostly semantic in nature. It may be that the expectations/language used on tests has changed since I wrote them.

**Comment by dhollinger** [comment]
@thebaron sounds simple enough - could you fix them and then I'll merge it?

**Comment by thebaron** [comment]
Surely. Lemme have a go real quick.

**Comment by thebaron** [comment]
It took 3 commits, but I think the rubocop linter is finally satisfied with the code there.

**Comment by dhollinger** [comment]
Merged

**Pull request merged**
