### PR TITLE
Add generate_types to Mcollective R10K plugin 

### PR DESCRIPTION
**Pull request by stanleyz**
This MR includes the following:

1. generate_types action to Mcollective R10K plugin
2. feature to kick off generate_types action from the webhook binary
3. Fix process fork issue introduced in previous commit 90da3cf

### CODE REVIEW

**Comment by stanleyz** [comment]
#293

**Comment by stanleyz** [comment]
is that because the user doesn't have permission to read puppet.conf?

**Comment by vchepkov** [comment]
That's a strange puppet's feature. You can check under unprivileged account:

```
$ puppet config print config
$ puppet config print|grep dir
```

They all will be in $HOME/.puppetlabs

**Comment by stanleyz** [comment]
yes, so I guess you could put the additional options to the puppet.conf of unprivileged users?

Of course we can change the code to allow additional parameters, but the additional options are global options not only related to `generate types` alone.

**Comment by jakegroves** [comment]
Is this still being looked into rebasing and merging?

**Comment by stanleyz** [comment]
No, sorry, I've been busy on something else.

**Comment by igalic** [comment]
can we transfer what's here (also) into a bolt task?

**Comment by bastelfreak** [comment]
I think we can close this now because r10k supports the type generation.

**Pull request closed without merging**
