### PR TITLE
Puppet4aio

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by rnelson0** [comment]
We'll get this when we do the modulesync - I hate Syck.

**Comment by ghoneycutt** [comment]
Could you please cherry pick bug fix 5a8bfd5cff3fa52e3dad346f2e131a98683abb7a

Any ETA on the modulesync?

**Comment by rnelson0** [comment]
I probably won't get to finish it today since I expect the first cut will throw a ton of errors, but check out #296. We'll make sure that change gets in there as well.

**Comment by ghoneycutt** [comment]
@rnelson0 since these tests passed and you are going to support Puppet v4 / Ruby 2.3.1, could you merge this as a stop gap until you have the modulesync bits working?

**Pull request closed without merging**
