### PR TITLE
Remove support for providers yum, zypper

### PR DESCRIPTION
**Pull request by dhoppe**
This pull request removes support for providers ```yum``` and ```zypper```. We also might want to remove support for OpenBSD and remove the ```package``` resource, since this was introduced for Puppet Enterprise which has ```r10k``` already installed.

This will fix issue #449.

### CODE REVIEW

**Comment by alexjfisher** [comment]
This package https://software.opensuse.org/download.html?project=systemsmanagement%3Apuppet&package=rubygem-r10k isn't that old...

**Comment by dhoppe** [comment]
@alexjfisher Hm. I missed that somehow and will drop the latest commit. Interesting that SLES provides a package and RHEL does not. Usually it is the other way around.

**Comment by rnelson0** [comment]
r10k 2.3.0 was released on May 18, 2016 (current is 3.2.0 from April 16, 2019), so I'm not sure that I would say the packages are anything near recent, even if the timestamps are.

**Comment by dhoppe** [comment]
Someone needs to make a decision. I still think we should remove yum and zypper, because it does not hurt to install a gem.

**Comment by bastelfreak** [comment]
let's keep it open for 3 more days. I'm :+1: for dropping it. If nobody offers an argument to keep it, we can drop it.

**Pull request merged**
