### PR TITLE
rewrite CHANGELOG to markdown

### PR DESCRIPTION
**Pull request by bastelfreak**
our release process requires a `CHANGELOG.md`

```
$ bundle exec rake travis_release
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - CHANGELOG.md
/home/bastelfreak/modulesync_config/modules/puppet-r10k/.vendor/ruby/2.3.0/bundler/gems/voxpupuli-release-gem-4fc386d54c92/lib/voxpupuli/release/rake_tasks.rb:37:in `readlines'
/home/bastelfreak/modulesync_config/modules/puppet-r10k/.vendor/ruby/2.3.0/bundler/gems/voxpupuli-release-gem-4fc386d54c92/lib/voxpupuli/release/rake_tasks.rb:37:in `block in <top (required)>'
/home/bastelfreak/modulesync_config/modules/puppet-r10k/.vendor/ruby/2.3.0/bundler/gems/voxpupuli-release-gem-4fc386d54c92/lib/voxpupuli/release/rake_tasks.rb:16:in `block in <top (required)>'
/home/bastelfreak/modulesync_config/modules/puppet-r10k/.vendor/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/bastelfreak/.gem/ruby/2.3.0/gems/bundler-1.13.3/lib/bundler/cli/exec.rb:74:in `load'
/home/bastelfreak/.gem/ruby/2.3.0/gems/bundler-1.13.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/bastelfreak/.gem/ruby/2.3.0/gems/bundler-1.13.3/lib/bundler/cli/exec.rb:27:in `run'
/home/bastelfreak/.gem/ruby/2.3.0/gems/bundler-1.13.3/lib/bundler/cli.rb:332:in `exec'
/home/bastelfreak/.gem/ruby/2.3.0/gems/bundler-1.13.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/bastelfreak/.gem/ruby/2.3.0/gems/bundler-1.13.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/bastelfreak/.gem/ruby/2.3.0/gems/bundler-1.13.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/bastelfreak/.gem/ruby/2.3.0/gems/bundler-1.13.3/lib/bundler/cli.rb:20:in `dispatch'
/home/bastelfreak/.gem/ruby/2.3.0/gems/bundler-1.13.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/bastelfreak/.gem/ruby/2.3.0/gems/bundler-1.13.3/lib/bundler/cli.rb:11:in `start'
/home/bastelfreak/.gem/ruby/2.3.0/gems/bundler-1.13.3/exe/bundle:34:in `block in <top (required)>'
/home/bastelfreak/.gem/ruby/2.3.0/gems/bundler-1.13.3/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/home/bastelfreak/.gem/ruby/2.3.0/gems/bundler-1.13.3/exe/bundle:26:in `<top (required)>'
/home/bastelfreak/.gem/ruby/2.3.0/bin/bundle:23:in `load'
/home/bastelfreak/.gem/ruby/2.3.0/bin/bundle:23:in `<main>'
Tasks: TOP => check_changelog
(See full trace by running task with --trace)
```

### CODE REVIEW

**Comment by alexjfisher** [comment]
Can we add the release date to at least the last couple of releases?

**Comment by alexjfisher** [comment]
Maybe in place of `- multiple authors` that doesn't add any real value?

**Comment by ghoneycutt** [comment]
+1 as every release should have multiple authors - the person doing the change and someone else that merged it.

**Comment by rnelson0** [comment]
Superseded by #301.

**Pull request closed without merging**
