### PR TITLE
Webhook Background mode

### PR DESCRIPTION
**Pull request by luckyraul**
option for docker

### CODE REVIEW

**Comment by rnelson0** [comment]
@luckyraul Can you describe the difference between these two modes, why a user would want to use one or the other? I'm personally curious, but that should also go somewhere in the readme.

**Comment by luckyraul** [comment]
@rnelson0 

To run webhook as the main process in Docker

**Comment by rnelson0** [comment]
@luckyraul OK, can you add something to the readme then so users are aware of the option and use case, please?

**Comment by luckyraul** [comment]
@rnelson0  check please

**Comment by luckyraul** [comment]
My text is "If you are building your image with the puppet"

**Comment by rnelson0** [comment]
What does that mean? Are you talking about the [image_build module](https://forge.puppet.com/puppetlabs/image_build)?

**Comment by luckyraul** [comment]
It can be that module, or just puppet apply inside the docker's RUN.

**Pull request merged**
