### PR TITLE
Update config_version.sh

### PR DESCRIPTION
**Pull request by seanscottking**
I revised your example `config_version.sh` a bit. The major change is that I shortened the result of the SHA code to the first 10 characters. A complete SHA is like 40 characters. I like the cleaner output and thought others would too.

The rest of the changes are simply setting variables at the top of the file for easier configurability/readability

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Using the full SHA is safer and more accurate.

**Comment by rnelson0** [comment]
I agree with @ghoneycutt.  The rest of the change improves legibility, though.

**Comment by seanscottking** [comment]
Came for the SHA, stay for the ${VAR} 💯

**Comment by ghoneycutt** [comment]
Forgot about #288 .. I need help figuring out why bundler isn't behaving as it should.

**Comment by seanscottking** [comment]
Sorry, I don't know bundler at all

**Comment by rnelson0** [comment]
@seanscottking can you rebate this? It should pass tests now, or at least fail on related changes :)

**Comment by seanscottking** [comment]
OK rebased. Tests are taking a while, let's see if they pass

**Pull request merged**
