### PR TITLE
Release 7.0.0

### PR DESCRIPTION
**Pull request by rnelson0**
Will update the changelog after work.

### CODE REVIEW

**Comment by rnelson0** [comment]
Tests are failing due to puppetlabs/ruby requiring a new build.

**Comment by rnelson0** [comment]
puppetlabs/ruby got a new release and now the tests pass. I won't be able to do the changelog until after work again.

**Comment by 0x6d617474** [comment]
Can we get #495 merged before release? It is a quick fix followup to #485 that makes the slack_icon feature introduced actually usable.

**Comment by rnelson0** [comment]
Yeah, I can hold on for that.

**Pull request merged**
