### PR TITLE
Make `status_code` entries consistent, and switch to using `status_message` for success/fail symbols

### PR DESCRIPTION
**Pull request by legooolas**
#### Pull Request (PR) description

This change corrects the status_code entries to all be 202, but switches the status_message case statments to use the status field and the success/fail symbols instead of the numerical status codes. This stops it from needing to exactly match the status code.

#### This Pull Request (PR) fixes the following issues

n/a

### CODE REVIEW

**Comment by legooolas** [comment]
Split from PR #442 to avoid mashing the two changes together.

**Comment by rnelson0** [comment]
For consistency, should [this line](https://github.com/legooolas/puppet-r10k/blob/f586494699345dd1e247f3727556ef8bda17c42e/templates/webhook.bin.erb#L89) have a `:status_code` as well?

**Comment by bastelfreak** [comment]
can you please rebase against our latest master branch? That should fix the travis errors.

**Comment by dhoppe** [comment]
@legooolas Could please do a rebase? This pull request is tested against old versions of Puppet. For example, we dropped support for Puppet 4 two months ago.

**Comment by legooolas** [comment]
> @legooolas Could please do a rebase? This pull request is tested against old versions of Puppet. For example, we dropped support for Puppet 4 two months ago.

I should probably drop this request as I'm not going to be able to test it against recent versions of Puppet anytime soon, unfortunately.  I'll make a new PR if I can get to it again at some point in the future, sorry!

**Comment by rnelson0** [comment]
@legooolas That's understandable, just open a new PR when you are ready. Thanks!

**Pull request closed without merging**
